#!/usr/local/bin/node

// basias_convert_csv
// Created by Mathilde Ressier
// 30/03/2020
// 
// Read and convert basias files to CSV format

const { convertBasiasTextFilesToCSV } = require("./Sources/Conversion/convertBasiasTextFilesToCSV");
const { filterBasiasValidFilename } = require("./Sources/Tools/filterBasiasValidFilename");

///
/// BODY
///
let parameters = process.argv.slice(2)
let globalFilePath =  "BASIAS_COMPLETE.csv"

let filenames = filterBasiasValidFilename(parameters)

if (filenames.length == 0) {
    console.log("Usage: " + process.argv[0] + "[basias-files.txt]")
}

convertBasiasTextFilesToCSV(filenames, globalFilePath)
